// src/lib/components/RichTextEditor.svelte
<script lang="ts">
  import { CursorAwareness } from "loro-prosemirror";
  import { createEditor } from "prosekit/core";
  import { defineLoro } from "prosekit/extensions/loro";
  import { ProseKit } from "prosekit/svelte";
  import type { LoroDocType } from "../../sdk";

  let { doc }: { doc: LoroDocType } = $props();

  const editor = createEditor({
    extension: defineLoro({
      doc,
      awareness: new CursorAwareness(doc.peerIdStr),
    }),
  });

  const mount = (element: HTMLElement) => {
    editor.mount(element);
    return { destroy: () => editor.unmount() };
  };
</script>

<ProseKit {editor}>
  <div use:mount style="outline: auto; padding: 1rem"></div>
</ProseKit>

// src/components/RichTextEditor.vue
<template>
  <ProseKit :editor="editor">
    <div ref="editorRef" style="outline: auto; padding: 1rem" />
  </ProseKit>
</template>

<script setup lang="ts">
import 'prosekit/basic/style.css'
import 'prosekit/basic/typography.css'

import { createEditor } from 'prosekit/core'
import { defineLoro } from 'prosekit/extensions/loro'
import { ProseKit } from 'prosekit/vue'
import {
  CursorAwareness,
  type LoroDocType
} from 'loro-prosemirror'
import {
  ref,
  watchPostEffect,
} from 'vue'

const { doc } = defineProps<{
  doc: LoroDocType
}>();

const awareness = new CursorAwareness(doc.peerIdStr)
const extension = defineLoro({ doc: doc, awareness })
const editor = createEditor({ extension })

const editorRef = ref<HTMLDivElement | null>(null)
watchPostEffect((onCleanup) => {
  editor.mount(editorRef.value)
  onCleanup(() => editor.unmount())
})
</script>
